### PR TITLE
Add sortField config option

### PR DESCRIPTION
**Pull request by johanmeiring**
This PR adds the `sortField` config option.  If set, the query that is used to determine the next value in for `sequenceField` will `ORDER BY` the `sortField` instead of the `sequenceField`.  In our case, we had to set this to the autoincrement primary key of the table for performance reasons.  The change resulted in a query which was around 3x faster.

### CODE REVIEW

**Comment by ADmad** [comment]
Why can't you just index the position column?

I don't see how ordering by primary key fields instead of the position field to get the highest order can work for every case. It's very possible that a record with largest id is set at first position. Then the higest order will be incorrectly returned as `1`.

**Comment by johanmeiring** [comment]
The sequence and scope columns were both indexed together.  As tables become larger it seems that Innodb performance on MySQL 5.6 becomes progressively worse when performing ORDER BY x DESC, even on indexed columns.  However the same problem does not apply to sorting by the primary key in descending order (at least not to the same degree, and which was easily confirmed in our testing).  Unfortunately we're constrained to using MySQL 5.6 for the foreseeable future.  The manner in which indices are created changed in 5.7, and in 8.0 it's even possible to explicitly define the direction of the index (ASC/DESC).

> I don't see how ordering by primary key field instead of the position field to get the highest order can work for every case.

It probably won't :-)  Especially if the primary key is non-numeric (UUID, for example).  That's why the submitted work has the sortField as being absolutely optional, and it should ideally only be used if you know what you're doing.  In our case, it brought about a significant performance improvement without compromises data integrity.

**Comment by ADmad** [comment]
I am sorry but your needs are pretty edge case and given the fact the using the new feature can result in incorrect position being set, I am not interested in adding a footgun.

You'll have to use your own customized version for your needs.

**Comment by johanmeiring** [comment]
Good call actually.  We recently upgraded our database instance size and I haven't run the same performance tests again until just now.  Seems both queries perform almost equally well, so we'll likely not need to use the fork after all.

Thank you for your kind feedback.  I've certainly never been accused of developing "footguns" before now 😂

**Pull request closed without merging**
